name: Playwright and BDD Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      # Normal Playwright tests
      # Includes:
      # - Direct UI test
      # - POM UI test
      # - Direct API tests
      # - API Client tests
      - name: Run Normal Playwright Tests
        run: npx playwright test --project=chromium
        env:
          ENV: test
          HEADLESS: true

      # Cucumber BDD tests
      # Includes:
      # - BDD UI with POM
      # - BDD API with API Client
      - name: Run Cucumber BDD Tests
        run: npm run bdd
        env:
          ENV: test
          HEADLESS: true

      # Upload Playwright HTML report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      # Upload Cucumber report + videos
      - name: Upload Cucumber BDD Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/
          retention-days: 7